[tool.poetry]
name = "crescendo"
version = "0.1.0"
description = ""
authors = ["tgoddessana <twicegoddessana1229@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"
djangorestframework = "^3.14.0"
djangorestframework-simplejwt = "^5.2.2"
cx-oracle = "^8.3.0"
gunicorn = "^21.2.0"
python-dotenv = "^1.0.0"
django-storages = "^1.13.2"
pillow = "^10.0.0"
boto3 = "^1.28.12"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
django-debug-toolbar = "^4.1.0"
django-extensions = "^3.2.3"
ipython = "^8.14.0"
pre-commit = "^3.3.3"
mypy = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
