# Generated by Django 4.2.4 on 2023-08-12 14:24

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("studygroup", "0001_initial"),
        ("studygroup", "0002_alter_studygroup_tags"),
        ("studygroup", "0003_alter_promotionpost_study_group_and_more"),
        (
            "studygroup",
            "0004_remove_studygroup_deadline_promotionpost_deadline_and_more",
        ),
        ("studygroup", "0005_alter_promotionpost_study_group"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=80)),
                ("user_limit", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="study_groups", to="studygroup.category"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="study_groups", to="studygroup.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "StudyGroup",
                "verbose_name_plural": "StudyGroups",
            },
        ),
        migrations.CreateModel(
            name="StudyGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_leader", models.BooleanField(default=False)),
                (
                    "studygroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studygroup_members",
                        to="studygroup.studygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studygroup_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "StudyGroup Members",
                "verbose_name_plural": "StudyGroup Members",
            },
        ),
        migrations.CreateModel(
            name="PromotionPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "head_image",
                    models.ImageField(blank=True, upload_to="studygroup/head_image"),
                ),
                ("title", models.CharField(max_length=64)),
                ("content", models.TextField(max_length=3000)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studygroup.studygroup",
                    ),
                ),
                ("deadline", models.DateField(default=datetime.date(2023, 8, 12))),
            ],
            options={
                "verbose_name": "Promotion Post",
                "verbose_name_plural": "Promotion Posts",
            },
        ),
    ]
