# Generated by Django 4.2.4 on 2023-08-20 13:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studygroup", "0002_alter_promotionpost_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studygroupmember",
            name="studygroup",
        ),
        migrations.RemoveField(
            model_name="studygroupmember",
            name="user",
        ),
        migrations.AddField(
            model_name="studygroup",
            name="content",
            field=models.TextField(default="content", max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studygroup",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studygroup",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="studygroup/head_image"),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="leader",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managing_study_groups",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studygroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_study_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="title",
            field=models.CharField(default="title", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="user_limit",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="PromotionPost",
        ),
        migrations.DeleteModel(
            name="StudyGroupMember",
        ),
    ]
