# Generated by Django 4.2.4 on 2023-08-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studygroup", "0004_rename_user_limit_studygroup_member_limit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studygroup",
            options={
                "ordering": ["-pk"],
                "verbose_name": "StudyGroup",
                "verbose_name_plural": "StudyGroups",
            },
        ),
        migrations.RemoveField(
            model_name="studygroup",
            name="leader",
        ),
        migrations.CreateModel(
            name="StudyGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_leader", models.BooleanField(default=False)),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_group_members",
                        to="studygroup.studygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_group_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "StudyGroup Member",
                "verbose_name_plural": "StudyGroup Members",
            },
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_study_groups",
                to="studygroup.studygroupmember",
            ),
        ),
    ]
