# Generated by Django 4.2.4 on 2023-08-23 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "studygroup",
            "0005_alter_studygroup_options_remove_studygroup_leader_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studygroupmember",
            unique_together={("user", "study_group")},
        ),
    ]
