# Generated by Django 4.2.4 on 2023-08-24 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0006_alter_studygroupmember_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studygroupmember",
            unique_together=set(),
        ),
    ]
