# Generated by Django 4.2.4 on 2023-08-24 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studygroup", "0007_alter_studygroupmember_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studygroupmember",
            unique_together={("user", "study_group")},
        ),
    ]
