# Generated by Django 4.2.4 on 2023-08-24 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studygroup", "0008_alter_studygroupmember_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studygroup",
            name="members",
        ),
        migrations.AlterField(
            model_name="studygroupmember",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_group_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
