# Generated by Django 4.2.4 on 2023-08-24 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studygroup", "0009_remove_studygroup_members_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studygroupmember",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="studygroupmember",
            name="study_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="studygroup.studygroup",
            ),
        ),
        migrations.AlterField(
            model_name="studygroupmember",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_group_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="studygroupmember",
            constraint=models.UniqueConstraint(
                fields=("user", "study_group"), name="unique_study_group_member"
            ),
        ),
    ]
