# Generated by Django 4.2.4 on 2023-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0012_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="studygroup/head_images/%Y/%m/%d"
            ),
        ),
    ]
