# Generated by Django 4.2.4 on 2023-09-26 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0013_alter_studygroup_head_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroupmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studygroupmember",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studygroupmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
