# Generated by Django 4.2.4 on 2023-09-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0014_studygroupmember_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroupmember",
            name="request_message",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
