# Generated by Django 4.2.6 on 2023-10-09 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studygroup", "0015_studygroupmember_request_message"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studygroupmember",
            name="unique_study_group_member",
        ),
        migrations.RenameField(
            model_name="studygroupmember",
            old_name="study_group",
            new_name="studygroup",
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="categories",
            field=models.ManyToManyField(
                related_name="studygroups", to="studygroup.category"
            ),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="studygroups", to="studygroup.tag"
            ),
        ),
        migrations.AlterField(
            model_name="studygroupmember",
            name="request_message",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="studygroupmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studygroup_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="studygroupmember",
            constraint=models.UniqueConstraint(
                fields=("user", "studygroup"), name="unique_studygroup_member"
            ),
        ),
    ]
