# Generated by Django 4.2.6 on 2023-10-09 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "studygroup",
            "0016_remove_studygroupmember_unique_study_group_member_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studygroupmember",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="studygroupmember",
            name="request_message",
        ),
        migrations.CreateModel(
            name="StudyGroupMemberRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_message", models.CharField(max_length=200)),
                ("processed", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "studygroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="studygroup.studygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studygroup_member_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
