# Generated by Django 4.2.6 on 2023-10-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0017_remove_studygroupmember_is_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=64)),
                ("content", models.TextField(max_length=1500)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="studygroup.studygroupmember",
                    ),
                ),
                (
                    "studygroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="studygroup.studygroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
