# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0018_assignmentrequest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssignmentRequest",
            new_name="StudyGroupAssignmentRequest",
        ),
    ]
