# Generated by Django 4.2.6 on 2023-10-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0020_studygroupassignmentsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroupassignmentsubmission",
            name="assignment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="studygroup.studygroupassignmentrequest",
            ),
        ),
    ]
