# Generated by Django 4.2.6 on 2023-10-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0021_alter_studygroupassignmentsubmission_assignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studygroupassignmentsubmission",
            options={
                "verbose_name": "StudyGroup Assignment Submission",
                "verbose_name_plural": "StudyGroup Assignment Submissions",
            },
        ),
        migrations.AlterField(
            model_name="studygroupassignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="studygroup.studygroupassignmentrequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="studygroupassignmentsubmission",
            constraint=models.UniqueConstraint(
                fields=("author", "assignment"), name="unique_assignment_submission"
            ),
        ),
    ]
