# Generated by Django 4.2.6 on 2023-12-07 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "studygroup",
            "0023_rename_studygroupassignmentrequest_assignmentrequest_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "StudyGroup Assignment Request",
                "verbose_name_plural": "StudyGroup Assignment Requests",
            },
        ),
    ]
