# Generated by Django 4.2.6 on 2024-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0024_alter_assignmentrequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroupmemberrequest",
            name="request_message",
            field=models.CharField(max_length=500),
        ),
    ]
