"""empty message

Revision ID: 00021567547c
Revises: 807142730228
Create Date: 2023-04-12 17:51:28.030331

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00021567547c"
down_revision = "807142730228"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=5),
            nullable=False,
            existing_server_default=sa.text("'USER'"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=5),
            nullable=True,
            existing_server_default=sa.text("'USER'"),
        )

    # ### end Alembic commands ###
