"""empty message

Revision ID: 09f4861cbacf
Revises: 
Create Date: 2023-04-02 15:18:32.857372

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "09f4861cbacf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("gender", sa.Enum("남자", "여자"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("User")
    # ### end Alembic commands ###
