"""empty message

Revision ID: 0ce62301a77c
Revises: c3790d26f0f2
Create Date: 2023-04-23 00:26:07.147045

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ce62301a77c"
down_revision = "c3790d26f0f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_study_uuid"), ["uuid"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("study_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_user_email"), ["email"])
        batch_op.create_unique_constraint(batch_op.f("uq_user_username"), ["username"])
        batch_op.create_unique_constraint(batch_op.f("uq_user_uuid"), ["uuid"])
        batch_op.create_foreign_key(
            batch_op.f("fk_user_study_id_study"), "study", ["study_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_study_id_study"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("uq_user_uuid"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_user_username"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_user_email"), type_="unique")
        batch_op.drop_column("study_id")

    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_study_uuid"), type_="unique")

    # ### end Alembic commands ###
