"""empty message

Revision ID: 0ed38e40c379
Revises: 37bb5bd6a7d2
Create Date: 2023-07-08 21:39:52.310467

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ed38e40c379"
down_revision = "37bb5bd6a7d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AUTH_ROLE",
        sa.Column("name", sa.String(length=15), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_AUTH_ROLE")),
    )
    op.create_table(
        "STUDY_CATEGORY",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_STUDY_CATEGORY")),
        sa.UniqueConstraint("name", name=op.f("uq_STUDY_CATEGORY_name")),
    )
    op.create_table(
        "STUDY_TAG",
        sa.Column("name", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_STUDY_TAG")),
    )
    op.create_table(
        "AUTH_USER",
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["AUTH_ROLE.id"], name=op.f("fk_AUTH_USER_role_id_AUTH_ROLE")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_AUTH_USER")),
        sa.UniqueConstraint("email", name=op.f("uq_AUTH_USER_email")),
        sa.UniqueConstraint("uuid", name=op.f("uq_AUTH_USER_uuid")),
    )
    op.create_table(
        "STUDY_STUDYGROUP",
        sa.Column("leader_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("user_limit", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["leader_id"],
            ["AUTH_USER.id"],
            name=op.f("fk_STUDY_STUDYGROUP_leader_id_AUTH_USER"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_STUDY_STUDYGROUP")),
        sa.UniqueConstraint("uuid", name=op.f("uq_STUDY_STUDYGROUP_uuid")),
    )
    op.create_table(
        "STUDY_CATEGORY_TO_STUDYGROUP",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("studygroup_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["STUDY_CATEGORY.id"],
            name=op.f("fk_STUDY_CATEGORY_TO_STUDYGROUP_category_id_STUDY_CATEGORY"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studygroup_id"],
            ["STUDY_STUDYGROUP.id"],
            name=op.f("fk_STUDY_CATEGORY_TO_STUDYGROUP_studygroup_id_STUDY_STUDYGROUP"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "category_id", "studygroup_id", name=op.f("pk_STUDY_CATEGORY_TO_STUDYGROUP")
        ),
    )
    op.create_table(
        "STUDY_CATEGORY_TO_USER",
        sa.Column("studygroup_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["studygroup_id"],
            ["STUDY_STUDYGROUP.id"],
            name=op.f("fk_STUDY_CATEGORY_TO_USER_studygroup_id_STUDY_STUDYGROUP"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["AUTH_USER.id"],
            name=op.f("fk_STUDY_CATEGORY_TO_USER_user_id_AUTH_USER"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "studygroup_id", "user_id", name=op.f("pk_STUDY_CATEGORY_TO_USER")
        ),
    )
    op.create_table(
        "STUDY_RECRUITMENT_POST",
        sa.Column("studygroup_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("content", sa.String(length=3000), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["studygroup_id"],
            ["STUDY_STUDYGROUP.id"],
            name=op.f("fk_STUDY_RECRUITMENT_POST_studygroup_id_STUDY_STUDYGROUP"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_STUDY_RECRUITMENT_POST")),
        sa.UniqueConstraint("uuid", name=op.f("uq_STUDY_RECRUITMENT_POST_uuid")),
    )
    op.create_table(
        "STUDY_TAG_TO_STUDYGROUP",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("studygroup_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["studygroup_id"],
            ["STUDY_STUDYGROUP.id"],
            name=op.f("fk_STUDY_TAG_TO_STUDYGROUP_studygroup_id_STUDY_STUDYGROUP"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["STUDY_TAG.id"],
            name=op.f("fk_STUDY_TAG_TO_STUDYGROUP_tag_id_STUDY_TAG"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tag_id", "studygroup_id", name=op.f("pk_STUDY_TAG_TO_STUDYGROUP")
        ),
    )
    op.create_table(
        "STUDY_RECRUITMENT_HISTORY",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["STUDY_RECRUITMENT_POST.id"],
            name=op.f("fk_STUDY_RECRUITMENT_HISTORY_post_id_STUDY_RECRUITMENT_POST"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["AUTH_USER.id"],
            name=op.f("fk_STUDY_RECRUITMENT_HISTORY_user_id_AUTH_USER"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_STUDY_RECRUITMENT_HISTORY")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("STUDY_RECRUITMENT_HISTORY")
    op.drop_table("STUDY_TAG_TO_STUDYGROUP")
    op.drop_table("STUDY_RECRUITMENT_POST")
    op.drop_table("STUDY_CATEGORY_TO_USER")
    op.drop_table("STUDY_CATEGORY_TO_STUDYGROUP")
    op.drop_table("STUDY_STUDYGROUP")
    op.drop_table("AUTH_USER")
    op.drop_table("STUDY_TAG")
    op.drop_table("STUDY_CATEGORY")
    op.drop_table("AUTH_ROLE")
    # ### end Alembic commands ###
