"""empty message

Revision ID: 37bb5bd6a7d2
Revises: 
Create Date: 2023-06-25 02:30:24.320225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37bb5bd6a7d2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_category",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_category")),
        sa.UniqueConstraint("name", name=op.f("uq_study_category_name")),
    )
    op.create_table(
        "study_study",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_study")),
        sa.UniqueConstraint("uuid", name=op.f("uq_study_study_uuid")),
    )
    op.create_table(
        "auth_user",
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column("role", sa.String(length=10), server_default="USER", nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["study_study.id"],
            name=op.f("fk_auth_user_study_id_study_study"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_user")),
        sa.UniqueConstraint("email", name=op.f("uq_auth_user_email")),
        sa.UniqueConstraint("uuid", name=op.f("uq_auth_user_uuid")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_user")
    op.drop_table("study_study")
    op.drop_table("study_category")
    # ### end Alembic commands ###
