"""empty message

Revision ID: 527f3b5ee5cd
Revises: ddaffb2517bc
Create Date: 2023-06-25 01:59:50.138945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "527f3b5ee5cd"
down_revision = "ddaffb2517bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_category",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_category")),
        sa.UniqueConstraint("name", name=op.f("uq_study_category_name")),
    )
    op.create_table(
        "study_study",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_study")),
        sa.UniqueConstraint("uuid", name=op.f("uq_study_study_uuid")),
    )
    op.create_table(
        "auth_user",
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column("role", sa.String(length=10), server_default="USER", nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["study_study.id"],
            name=op.f("fk_auth_user_study_id_study_study"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_user")),
        sa.UniqueConstraint("email", name=op.f("uq_auth_user_email")),
        sa.UniqueConstraint("uuid", name=op.f("uq_auth_user_uuid")),
    )
    op.drop_table("user")
    op.drop_table("category")
    op.drop_table("study")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study",
        sa.Column("name", sa.VARCHAR(length=80), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("uuid", sa.VARCHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid", name="uq_study_uuid"),
    )
    op.create_table(
        "category",
        sa.Column("name", sa.VARCHAR(length=20), nullable=False),
        sa.Column("description", sa.VARCHAR(length=100), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_category"),
        sa.UniqueConstraint("name", name="uq_category_name"),
    )
    op.create_table(
        "user",
        sa.Column("email", sa.VARCHAR(length=80), nullable=False),
        sa.Column("username", sa.VARCHAR(length=10), nullable=False),
        sa.Column(
            "role",
            sa.VARCHAR(length=10),
            server_default=sa.text("'USER'"),
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("uuid", sa.VARCHAR(length=36), nullable=False),
        sa.Column("study_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_id"], ["study.id"], name="fk_user_study_id_study"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_user_email"),
        sa.UniqueConstraint("uuid", name="uq_user_uuid"),
    )
    op.drop_table("auth_user")
    op.drop_table("study_study")
    op.drop_table("study_category")
    # ### end Alembic commands ###
