"""empty message

Revision ID: 7aa80c778e19
Revises: f7cfbcd9eb81
Create Date: 2023-06-05 22:22:28.846662

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7aa80c778e19"
down_revision = "f7cfbcd9eb81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_username", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_user_username", ["username"])

    # ### end Alembic commands ###
