"""empty message

Revision ID: 7d7a5211d824
Revises: 3f3c4588618e
Create Date: 2023-03-05 10:14:16.492431

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7d7a5211d824"
down_revision = "3f3c4588618e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.alter_column("created_on", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("updated_on", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column(
            "uuid", existing_type=sa.VARCHAR(length=36), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.alter_column(
            "uuid", existing_type=sa.VARCHAR(length=36), nullable=True
        )
        batch_op.alter_column("updated_on", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("created_on", existing_type=sa.DATETIME(), nullable=True)

    # ### end Alembic commands ###
