"""empty message

Revision ID: 807142730228
Revises: 
Create Date: 2023-04-12 17:47:09.767701

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "807142730228"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "STAFF", "USER", name="roleenum"),
            server_default="USER",
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
