"""empty message

Revision ID: c3790d26f0f2
Revises: 4e5905cc08fa
Create Date: 2023-04-23 00:22:10.875828

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c3790d26f0f2"
down_revision = "4e5905cc08fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("study_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "study", ["study_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("study_id")

    # ### end Alembic commands ###
