"""empty message

Revision ID: ce3f4b0eecee
Revises: 0ed38e40c379
Create Date: 2023-07-08 22:37:05.028979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce3f4b0eecee"
down_revision = "0ed38e40c379"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("STUDY_RECRUITMENT_POST", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deadline", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("STUDY_RECRUITMENT_POST", schema=None) as batch_op:
        batch_op.drop_column("deadline")

    # ### end Alembic commands ###
