"""empty message

Revision ID: f7cfbcd9eb81
Revises: 0ce62301a77c
Create Date: 2023-06-05 15:22:12.227482

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f7cfbcd9eb81"
down_revision = "0ce62301a77c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=5),
            type_=sa.String(length=10),
            existing_nullable=False,
            existing_server_default=sa.text("'USER'"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.String(length=10),
            type_=sa.VARCHAR(length=5),
            existing_nullable=False,
            existing_server_default=sa.text("'USER'"),
        )

    # ### end Alembic commands ###
