# Generated by Django 4.2.4 on 2023-08-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="studygroup",
            options={
                "verbose_name": "StudyGroup",
                "verbose_name_plural": "StudyGroups",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AddField(
            model_name="studygroup",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="studygroup/head_image"),
        ),
    ]
