# Generated by Django 4.2.4 on 2023-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0001_studygroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionpost",
            name="deadline",
            field=models.DateField(),
        ),
    ]
