# Generated by Django 4.2.4 on 2023-08-09 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studygroup", "0002_alter_category_options_alter_studygroup_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
